# Nombre del sitio
site_name: Mi Documentación

# Tema del sitio
theme:
  name: mkdocs

# Páginas de la documentación
nav:
  - Home: index.md
  
# Extensiones de Markdown
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite

# Plugins
plugins:
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
  - search
  - techdocs-core



# Archivos extra de JavaScript
extra_javascript:
  - javascripts/pdf-button.js
