# Nombre del sitio
site_name: Mi Documentación

# Tema del sitio
theme:
  name: mkdocs

# Páginas de la documentación
nav:
  - Home: index.md

# Extensiones de Markdown
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite

# Plugins
plugins:
  - pdf-export
  - search
  - techdocs-core